name: Build, test, package

on: [push,pull_request]

env:
  itk-git-tag: "835dc01388d22c4b4c9a46b01dbdfe394ec23511"
  itk-wheel-tag: "v5.3rc04.post2"

jobs:
  itk-build-test-package:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package.yml
    with:
      itk-git-tag: ${{ env.itk-git-tag }}
      itk-wheel-tag: ${{ env.itk-wheel-tag }}
