name: Build, test, package

on: [push,pull_request]

env:
  itk-git-tag: "835dc01388d22c4b4c9a46b01dbdfe394ec23511"
  itk-wheel-tag: "v5.3rc04.post2"

jobs:
  itk-build-test-package:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package.yml@99fc57f875bdaf12e5be3d18bf2a35ff7f0d1fb6
    with:
      itk-git-tag: "835dc01388d22c4b4c9a46b01dbdfe394ec23511"
      itk-wheel-tag: "v5.3rc04.post2"
